version: '3'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: circleci-frontend-deploy_local
    tty: true
    volumes: 
      - ./src:/app
    ports:
      - 3000:3000
    working_dir: /app