version: 2.1
orbs:
    aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: 
          name: yarnパッケージの取得
          command: yarn install
          working_directory: src
      - run: 
          name: 静的サイトのビルド
          command: yarn generate
          working_directory: src
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - run: 
          name: テスト(Jest)
          command: yarn test
          working_directory: src
  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - aws-s3/sync:
          from: src/dist
          to: 's3://$AWS_TARGET_BUCKET'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

workflows:
  build-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test