version: 2.1
orbs:
    aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: /tmp/work
    steps:
      - checkout
      - restore_cache:
          name: Yarn パッケージのキャッシュの復元
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
          working_directory: src
      - run:
          name: 依存関係のインストール
          command: yarn install --frozen-lockfile
          working_directory: src
      - save_cache:
          name: Yarn パッケージのキャッシュの保存
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
          working_directory: src
      - run: 
          name: 静的サイトのビルド
          command: yarn generate
          working_directory: src
      - persist_to_workspace:
          root: .
          paths:
            - src

  test:
    docker:
      - image: circleci/node:lts
    working_directory: /tmp/work
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: テスト(Jest)
          command: yarn test
          working_directory: src
      - persist_to_workspace:
          root: .
          paths:
            - src

  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    working_directory: /tmp/work
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: src/dist
          to: 's3://$AWS_TARGET_BUCKET'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

workflows:
  build-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test